name: 'release-py'
description: 'Automated releases for Python projects - handles versioning, changelogs, and publishing'
author: 'Mikko Leppanen'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  command:
    description: |
      Command to run:
      - release-pr: Create/update a release pull request
      - release: Tag, publish to PyPI, and create GitHub release
      - check: Preview what would happen (dry-run)
      - check-pr: Validate PR title follows conventional commits
      - update: Update version and changelog locally
      - init: Initialize release-py configuration
    required: true

  github-token:
    description: 'GitHub token for PR/release creation. Pass ${{ github.token }} or a PAT.'
    required: false
    default: ''

  pypi-token:
    description: 'PyPI token for publishing (optional - uses trusted publishing if not provided)'
    required: false
    default: ''

  working-directory:
    description: 'Working directory for the command (defaults to repository root)'
    required: false
    default: '.'

  python-version:
    description: 'Python version to use (3.11, 3.12, or 3.13)'
    required: false
    default: '3.11'

  release-py-version:
    description: 'Version of release-py to install (default: latest). Use "source" to install from current repo.'
    required: false
    default: ''

  dry-run:
    description: 'Run in dry-run mode (no actual changes)'
    required: false
    default: 'false'

  skip-publish:
    description: 'Skip publishing to PyPI (release command only)'
    required: false
    default: 'false'

  require-scope:
    description: 'Require a scope in PR title (check-pr command only)'
    required: false
    default: 'false'

outputs:
  version:
    description: 'The version that was/would be released'
    value: ${{ steps.release-py.outputs.version }}

  pr-number:
    description: 'The PR number (for release-pr command)'
    value: ${{ steps.release-py.outputs.pr-number }}

  pr-url:
    description: 'The PR URL (for release-pr command)'
    value: ${{ steps.release-py.outputs.pr-url }}

  release-url:
    description: 'The GitHub release URL (for release command)'
    value: ${{ steps.release-py.outputs.release-url }}

  tag:
    description: 'The git tag created (for release command)'
    value: ${{ steps.release-py.outputs.tag }}

  valid:
    description: 'Whether PR title is valid (for check-pr command)'
    value: ${{ steps.release-py.outputs.valid }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        VALID_COMMANDS="release-pr release check check-pr update init"
        COMMAND="${{ inputs.command }}"
        if [[ ! " $VALID_COMMANDS " =~ " $COMMAND " ]]; then
          echo "::error::Invalid command '$COMMAND'. Must be one of: $VALID_COMMANDS"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install release-py
      shell: bash
      run: |
        if [[ "${{ inputs.release-py-version }}" == "source" ]]; then
          echo "Installing release-py from source..."
          uv tool install --from . release-py
        elif [[ -n "${{ inputs.release-py-version }}" ]]; then
          echo "Installing release-py==${{ inputs.release-py-version }}..."
          uv tool install "release-py==${{ inputs.release-py-version }}"
        else
          echo "Installing latest release-py..."
          uv tool install release-py
        fi

    - name: Run release-py
      id: release-py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        # Use provided token, fall back to github.token via workflow context
        GITHUB_TOKEN: ${{ inputs.github-token || github.token }}
        PYPI_TOKEN: ${{ inputs.pypi-token }}
        GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}
        # Disable Rich color output for reliable parsing
        NO_COLOR: '1'
        FORCE_COLOR: '0'
      run: |
        set -euo pipefail

        # Build command with options
        CMD="release-py ${{ inputs.command }}"

        # Add --dry-run for commands that support it
        if [[ "${{ inputs.dry-run }}" == "true" ]]; then
          case "${{ inputs.command }}" in
            release-pr|release|check)
              CMD="$CMD --dry-run"
              ;;
          esac
        fi

        # Add command-specific options
        if [[ "${{ inputs.command }}" == "release" && "${{ inputs.skip-publish }}" == "true" ]]; then
          CMD="$CMD --skip-publish"
        fi

        if [[ "${{ inputs.command }}" == "check-pr" && "${{ inputs.require-scope }}" == "true" ]]; then
          CMD="$CMD --require-scope"
        fi

        echo "::group::Running: $CMD"

        # Capture output and exit code separately
        set +e
        output=$($CMD 2>&1)
        exit_code=$?
        set -e

        echo "$output"
        echo "::endgroup::"

        # Parse outputs based on command
        case "${{ inputs.command }}" in
          release-pr)
            # Extract PR URL (format: "Created PR #123: https://..." or "Updated PR #123: https://...")
            pr_url=$(echo "$output" | grep -oE 'https://github\.com/[^/]+/[^/]+/pull/[0-9]+' | head -1 || true)
            if [[ -n "$pr_url" ]]; then
              echo "pr-url=$pr_url" >> "$GITHUB_OUTPUT"
              pr_number=$(echo "$pr_url" | grep -oE '[0-9]+$' || true)
              echo "pr-number=$pr_number" >> "$GITHUB_OUTPUT"
            fi
            # Extract next version (after arrow: "→ 1.2.3" or "→ [green]1.2.3")
            next_version=$(echo "$output" | grep -oE '→\s*\[?[a-z]*\]?v?[0-9]+\.[0-9]+\.[0-9]+[^\s\[]*' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+[a-zA-Z0-9.]*' | head -1 || true)
            if [[ -n "$next_version" ]]; then
              echo "version=$next_version" >> "$GITHUB_OUTPUT"
            fi
            ;;

          release)
            # Extract release URL
            release_url=$(echo "$output" | grep -oE 'https://github\.com/[^/]+/[^/]+/releases/tag/[^\s]+' | head -1 || true)
            if [[ -n "$release_url" ]]; then
              echo "release-url=$release_url" >> "$GITHUB_OUTPUT"
            fi
            # Extract tag (format: "Created and pushed tag v1.2.3")
            tag=$(echo "$output" | grep -oE 'pushed tag v?[0-9]+\.[0-9]+\.[0-9]+[^\s]*' | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+[^\s]*' | head -1 || true)
            if [[ -n "$tag" ]]; then
              echo "tag=$tag" >> "$GITHUB_OUTPUT"
            fi
            # Extract version from "Releasing project-name v1.2.3"
            version=$(echo "$output" | grep -oE 'Releasing .+ v[0-9]+\.[0-9]+\.[0-9]+' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+[^\s]*' | head -1 || true)
            if [[ -n "$version" ]]; then
              echo "version=$version" >> "$GITHUB_OUTPUT"
            fi
            ;;

          check-pr)
            if [[ $exit_code -eq 0 ]]; then
              echo "valid=true" >> "$GITHUB_OUTPUT"
            else
              echo "valid=false" >> "$GITHUB_OUTPUT"
            fi
            ;;

          check)
            # Extract next version from check output
            version=$(echo "$output" | grep -oE 'Next version:\s*v?[0-9]+\.[0-9]+\.[0-9]+' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)
            if [[ -n "$version" ]]; then
              echo "version=$version" >> "$GITHUB_OUTPUT"
            fi
            ;;
        esac

        # Exit with the original exit code
        exit $exit_code
